#Server Configuration
server:
  port: 8081

#Log Configuration
logging:
  config: classpath:log4j2.yaml
  level:
    org.springframework.web: INFO
    com.pku.ss.movienftserver: INFO

#MySql configuration
spring:
  datasource:
    url: jdbc:mysql://82.157.177.72:3306/movie_nft?characterEncoding=utf8&useAffectedRows=true
    username: root
    password: Qtum2021#
    driver-class-name: com.mysql.cj.jdbc.Driver

#FileStorage Configuration
fileStorage:
  path: /root/home/
  #path: D://images/

#QtumClient Configuration
qtumClient:
  url: http://152.136.130.81:8081/
  username: test
  password: test1234